# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('locations', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
